package com.bitbyte404.fastgradlecn

import java.io.File

object GradleInitScriptService {

    private val initDir = File(System.getProperty("user.home"), ".gradle/init.d")
    private val initFile = File(initDir, "cn-mirrors.init.gradle")

    private val INIT_SCRIPT_CONTENT = """
// Generated by FastGradleCN IntelliJ Plugin
// Applies Aliyun CN mirrors to all Gradle builds automatically.

def cnMirrors = [
    "https://maven.aliyun.com/repository/gradle-plugin",
    "https://maven.aliyun.com/repository/public",
    "https://maven.aliyun.com/repository/google"
]

// Modern Android projects (Gradle 7+): pluginManagement repositories
beforeSettings { settings ->
    cnMirrors.each { mirror ->
        settings.pluginManagement.repositories {
            maven { url mirror }
        }
    }
}

// Modern Android projects: dependencyResolutionManagement repositories
settingsEvaluated { settings ->
    try {
        settings.dependencyResolutionManagement.repositories {
            cnMirrors.each { mirror ->
                maven { url mirror }
            }
        }
    } catch (Exception ignored) {}
}

// Legacy projects: allprojects repositories
allprojects {
    buildscript.repositories {
        cnMirrors.each { mirror ->
            maven { url mirror }
        }
    }
    repositories {
        cnMirrors.each { mirror ->
            maven { url mirror }
        }
    }
}
""".trimIndent()

    fun isInstalled(): Boolean = initFile.exists()

    fun install(): Result<Unit> = runCatching {
        initDir.mkdirs()
        initFile.writeText(INIT_SCRIPT_CONTENT, Charsets.UTF_8)
    }

    fun uninstall(): Result<Unit> = runCatching {
        initFile.delete()
    }

    fun initFilePath(): String = initFile.absolutePath
}
